title: Bao Hoang
logo: "/images/BaoHoang.jpg?raw=true"
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  I am a 4th year Computer Engineering student at UCSD. 
  <br><br>
  I have experience in web development and front-end development. I am interested in working with data, cloud computing and finance. 
  My main goal right now is to gain more experience in front-end and then move to back-end development, so that I can work on full-stack development.
  I also hope that in the future I will get to work on data analytics as well.  
  <br><br>
  <a href="https://www.linkedin.com/in/bao-hoang-g/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
